### ISSUE TITLE
安装插件后，网易云点击无反应

### ISSUE THREAD

**Issue by hapeman0314** [BetterNCM/DowngradeOK#2]
问题描述：安装插件后，整个网易云点击无反应，无法播放音乐

BetterNCM版本：1.3.2
网易云版本：3.0.0.Beta(64位)(Build: 202460)Patch:aae5544

**Comment by std-microblock** [comment]
请先删除 InfLink 插件

**Comment by hapeman0314** [comment]
> 请先删除 InfLink 插件

没有安装这个插件，我只安装了 纯净分享链接 这一个插件 ，我试了一下卸载 纯净分享链接 之后只安装降级插件也无法使用。
你可以复现这个问题吗？

**Comment by std-microblock** [comment]
不能，可以群内找我远程
