### ISSUE TITLE
无法降级

### ISSUE THREAD

**Issue by HurtGhostMeow** [BetterNCM/DowngradeOK#6]
降级时PowerShell报错，如图

**Comment by HurtGhostMeow** [comment]
![image](https://github.com/BetterNCM/DowngradeOK/assets/56166464/28e22d66-ff07-4066-9eae-45b006eebc9d)

**Comment by Ghost-chu** [comment]
同复现此问题

**Comment by Ghost-chu** [comment]
看起来是因为 https://d1.music.126.net/dmusic/NeteaseCloudMusic_Music_official_2.10.12.201849_32.exe 下载链接被删除了
